# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perfiles.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='perfiles.proto',
  package='tutorial',
  syntax='proto3',
  serialized_pb=_b('\n\x0eperfiles.proto\x12\x08tutorial\"\xd3\x01\n\x06Perfil\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\'\n\x06preset\x18\x03 \x03(\x0b\x32\x17.tutorial.Perfil.Preset\x1aL\n\x06Preset\x12\x13\n\x0bvalorPreset\x18\x01 \x01(\t\x12-\n\tnumPreset\x18\x02 \x01(\x0e\x32\x1a.tutorial.Perfil.NumPreset\"2\n\tNumPreset\x12\x0b\n\x07PRESET1\x10\x00\x12\x0b\n\x07PRESET2\x10\x01\x12\x0b\n\x07PRESET3\x10\x02\",\n\x08Perfiles\x12 \n\x06perfil\x18\x01 \x03(\x0b\x32\x10.tutorial.Perfilb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PERFIL_NUMPRESET = _descriptor.EnumDescriptor(
  name='NumPreset',
  full_name='tutorial.Perfil.NumPreset',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRESET1', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRESET2', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRESET3', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=190,
  serialized_end=240,
)
_sym_db.RegisterEnumDescriptor(_PERFIL_NUMPRESET)


_PERFIL_PRESET = _descriptor.Descriptor(
  name='Preset',
  full_name='tutorial.Perfil.Preset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valorPreset', full_name='tutorial.Perfil.Preset.valorPreset', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numPreset', full_name='tutorial.Perfil.Preset.numPreset', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=188,
)

_PERFIL = _descriptor.Descriptor(
  name='Perfil',
  full_name='tutorial.Perfil',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='tutorial.Perfil.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='tutorial.Perfil.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preset', full_name='tutorial.Perfil.preset', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PERFIL_PRESET, ],
  enum_types=[
    _PERFIL_NUMPRESET,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=240,
)


_PERFILES = _descriptor.Descriptor(
  name='Perfiles',
  full_name='tutorial.Perfiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='perfil', full_name='tutorial.Perfiles.perfil', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=286,
)

_PERFIL_PRESET.fields_by_name['numPreset'].enum_type = _PERFIL_NUMPRESET
_PERFIL_PRESET.containing_type = _PERFIL
_PERFIL.fields_by_name['preset'].message_type = _PERFIL_PRESET
_PERFIL_NUMPRESET.containing_type = _PERFIL
_PERFILES.fields_by_name['perfil'].message_type = _PERFIL
DESCRIPTOR.message_types_by_name['Perfil'] = _PERFIL
DESCRIPTOR.message_types_by_name['Perfiles'] = _PERFILES

Perfil = _reflection.GeneratedProtocolMessageType('Perfil', (_message.Message,), dict(

  Preset = _reflection.GeneratedProtocolMessageType('Preset', (_message.Message,), dict(
    DESCRIPTOR = _PERFIL_PRESET,
    __module__ = 'perfiles_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.Perfil.Preset)
    ))
  ,
  DESCRIPTOR = _PERFIL,
  __module__ = 'perfiles_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Perfil)
  ))
_sym_db.RegisterMessage(Perfil)
_sym_db.RegisterMessage(Perfil.Preset)

Perfiles = _reflection.GeneratedProtocolMessageType('Perfiles', (_message.Message,), dict(
  DESCRIPTOR = _PERFILES,
  __module__ = 'perfiles_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Perfiles)
  ))
_sym_db.RegisterMessage(Perfiles)


# @@protoc_insertion_point(module_scope)
